### ISSUE TITLE
Seems to not work atm

### ISSUE THREAD

**Issue by ghost** [zdoherty/prom-corona#1]
Not sure if i am doing it wrong, but here is the error:

```
# ./convert.py backfill
Traceback (most recent call last):
  File "./convert.py", line 157, in <module>
    main()
  File "./convert.py", line 152, in main
    json.dump(backfill(), outfd, indent=2)
  File "./convert.py", line 122, in backfill
    metrics.extend(series.backfill(metric))
  File "./convert.py", line 83, in backfill
    't': int(round(date.timestamp() * 1000)),
AttributeError: 'datetime.datetime' object has no attribute 'timestamp'
```

**Comment by zdoherty** [comment]
hi @hagabla! thanks for the report.

I'm not sure if this is due to johns hopkins changing their timeseries format or from my script messing up. I'll look into it shortly, apologies for the delay!
